### PR TITLE
Feature/fixed currencies

### PR DESCRIPTION
**Pull request by trickystylo**
Hi,

Please I want to have a fixed price integration of our token.

Localpromo Euro
5HtYMme8QxH8CzQGCFQ1XUZ3Zf262tsvKpQtrpFEW9jU

1 Localpromo euro = € 1,-

LP€ = symbol

What else do you need from me?

Thanks

### CODE REVIEW

**Comment by arnaldoshz** [comment]
Hola,

Por favor, quiero tener una integración add it as a static currency

*Mango* 
F2h9nzjXJeeMVePUSgeneJTWXMwBQRxM6sCCHytrdPKB

Mcoin = símbolo


Gracias

**Comment by tubbynl** [comment]
Ola, currently we only support the concepts 
* Conversion rate based on VWAP to EUR/USD
* Fixed rate (shop only shows the used token, no conversion applied)

The feature you request is an addon on the first type but with an extra in-between conversion, what do you think @clipto or @G1zm0nl ?

**Comment by tubbynl** [comment]
and btw; that has nothing to do with this pull-request :)

**Comment by tubbynl** [comment]
and @trickystylo ; your request is the fixed rate concept

**Comment by arnaldoshz** [comment]
greetings, I have a small project I want to use create a token to use it as a means of payment in small businesses I am from Venezuela where there is an economic and political crisis political disagreements and stop counting the government has a cryptomenda project therefore to legalized the cryptoweights .. I would like your colobaracion and experience to know if with waves I can carry out that project means of payment

**Comment by aliamirliravi** [comment]
Hi please add fixed price for my waves token

Token Id :rf3GwXcLZkHyiRbCXwfHPVgeAAJ7Q9ojsD3ssvSRL55

Name : SilkRoadCoin

Price 1 SilkRoadCoin = 1€

**Review by aliamirliravi — CHANGES_REQUESTED** [review]
Hi please add fixed price for my waves token

Token Id :rf3GwXcLZkHyiRbCXwfHPVgeAAJ7Q9ojsD3ssvSRL55

Name : SilkRoadCoin

Price 1 SilkRoadCoin = 1€

**Comment by MC76** [comment]
HI
Can you integrateted token BITMINE?

Name: BITMINE
Token id: 3fYHZkhuc83bdnog1Pc5FHmvByKbobCsy7vaP6n1UiYh
Price fixed 1 euro.

PS. Version of plugin gateway v.0.5.1 crash with last woocommerce and wordpress. (instead 0.4.4 work fine)

**Comment by trickystylo** [comment]
> * Fixed rate

How can you make your coin a fix rate for your shop?

**Comment by getcyclos** [comment]
Hola,

Por favor, quiero tener una integración de un assets 

Cyclos
ID: CgJTsAXAupGXUCcEWb66w1cZyA1X7J6gmghhPCg6c2rc

CYC= símbolo

Token para la energía cinética del cuerpo humano a través del uso de la bicicleta mediante una app que mide sus kilómetros recorridos, la cuál permitirá la compra de productos e intercambio del token en la comunidad. 

Muchas Gracias

**Comment by MC76** [comment]
Hello, I am not a programmer
Il 03/03/2021 17:32:18, Cyclos <notifications@github.com> ha scritto:
Hola,
Por favor, quiero tener una integración de un assets
Cyclos
ID: CgJTsAXAupGXUCcEWb66w1cZyA1X7J6gmghhPCg6c2rc
CYC= símbolo
Token para la energía cinética del cuerpo humano a través del uso de la bicicleta mediante una app que mide sus kilómetros recorridos, la cuál permitirá la compra de productos e intercambio del token en la comunidad.
Muchas Gracias

**Pull request closed without merging**
